# https://taskfile.dev
version: '3'
vars:
  BINFILE: gitlab-vars

tasks:
  default:
    cmds:
      - go mod download
      - CGO_ENABLED=0 go build .
      - upx ./{{.BINFILE}}

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean